---
sudo: required

language: go
go:
  - "1.10.x"

env:
  - CHANGE_MINIKUBE_NONE_USER=true K8S_VER=1.9.0 MK_VER=0.25.2 K6T_VER=0.4.0 SRC="http://www.tinycorelinux.net/9.x/x86/release/Core-current.iso"

notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always

before_script:
  # Setup minikube
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v$K8S_VER/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v$MK_VER/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

  - sudo minikube start --vm-driver=none --kubernetes-version=v$K8S_VER
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

  - k_wait_all_running() { while [[ "$(kubectl get $1 --all-namespaces --field-selector=status.phase!=Running | wc -l)" -gt 1 ]]; do kubectl get $1 --all-namespaces ; sleep 6; done ; }

  # Deploy kubevirt
  - kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v$K6T_VER/kubevirt.yaml
  - k_wait_all_running pods

script:
  # Deploy manifests
  - kubectl apply -f manifests/example/endpoint-secret.yaml
  - kubectl apply -f manifests/controller/cdi-controller-deployment.yaml

  - make manifests/example/golden-pvc.yaml URI="$SRC"
  - kubectl apply -f manifests/example/golden-pvc.yaml

  - k_wait_all_running pods
  - kubectl get pods --all-namespaces

  - make test

before_deploy:
  - make controller importer
  - git config --local user.name "screeley44"
  - git config --local user.email "screeley@redhat.com"
  - source version && git tag "$(RELEASE_TAG)"
  # - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  skip_cleanup: true
  on:
    branch: master
    repo: kubevirt/containerized-data-importer
- provider: script
  script: make release
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    repo: kubevirt/containerized-data-importer
- provider: releases
  api_key:
    secure: "i57weqeibIvsHe1fHbqJQ4WsUGpjgl+TJZqzE5lTk/wcXNmQCHH2X9XbTsrFgmoOitnxQdduB9JzlKL3fwu2tAMA0P7k/RL0cOHUkLqIbd6G/hr3+XPNpfl4wtcoYA5vfiskIoZaTaJGFw9bEmAnPqbNQ35o1Ed9i3BWixrGIEfHFoIZNBygdbsR0oLuQgjjlMZmKKzktnYndhcbd43DwvqQ9o9+LlUJrznXZEKP7qxJdcg2ue01T8EN2T+vMaBj25geECciSLeL0g0cpvFlFVQ34yX2ZvIbnd0XgnaNKCNG9PN1k7JZX8vjCfUgeIaelTe0fYN5FDAO10CL/0ZBHTuyjcyOEMABLdG8dMbYVJi5mTtPgiCgNeVsj2zXAXRGIGeE7XUyKbYON0suejg1bLrFivsERgShaiGDkZDy6uSTXEHH0v/esIy07g3AIUyjr9r710tR0TVDMd2gyRL/lH8yEQdE/6Q5MSwiolrjv6e2FhZR+7H9KzcXjyBkH6xs7EzAzyzD4XN7BW2n8eAH/+Exl6LEdFqNDuguHDz/PwU+6GvEKzzNjMB4RVQY6YwzOAP/GS6Jbz7Ya5kmW1fNXECUPrSZuDZGp4cIsNhP9kHdu+Njt5sDMsy0Svqd3LvwRlAcgbFXemd7McdnrUjse73zJnHwOb7Koqk/Q9QHgYw="
  skip_cleanup: true
  overwrite: true
  file:
    - build/controller/tmp/*
    - build/importer/tmp/*
  on:
    tag: true

