sudo: required

language: go

go_import_path: kubevirt.io/containerized-data-importer

go:
- 1.11.5

services:
- docker

env:
  global:
  - DOCKER_TAG=$TRAVIS_TAG
  - secure: RWxtzwVEpMvaJlPUuRo+m6Kv9kJJFID7E0tdbE57d1XJN5nEq9ryxsTu8GIVHDPKIoUs0zqt4MtWi+4Wwb+21B2IoXJiHtc1YUex3L/6h64ztgH0iBjd/2Kv2piN4XVY9eYOUcu0PsSU0+Fv785rNfy2/LOi+3Bgs5d20AU9SZs2QDwKBlgWBXeJx7/aqLeytTUUX4tshBfQsxZkhYfVJgNcA1oUGtGS+zjeYVbmveLYQriOdQsfoWcfSZGumRSVH+jH7YCC2MXvIOfL131aOYm6CS0DlJTR3LDuBtI+9tP5C7eF+4nPO/kkIZzpz9RwkOZK2Ejn6D//unHgbyHqzoU4n4YZxw2DUonwXxCYieQ2nEZI5CQeoKXwV26ufdTvFGUYfYMUUnyk8phlP13eZEIoHNFJR2yeCSVSC6p82kpO0Drl+HJpnpo86IePwlcAp6tOekcGiDuM8i8bRmgPtWQzNxsE34OZ7v1j3S2nCrOgO8S9AE262nM3FsIGXCl2KTtKUDOSx0/1xx27tZhsqGDMOksdfdE6msFTJ1cEU53KoJfyyr1UUAtHfIpGLYu67C3tveBB4pcgvZ8SyiP50O8SQkQWX1ovJPj4kZYEx3PKAvTiwvDcCXU21uJH60Qa3lugiNfabmoX4mxjkRgiUswkW4P/Tc9avVa6g6EKnqA=

notifications:
  irc:
    channels:
    - chat.freenode.net#kubevirt
    on_success: change
    on_failure: always

install:
  - make generate-verify
  - make docker
  - make manifests
  - make olm-verify
  - make apidocs

before_script:

script:
- make goveralls
- make test-lint

after_script:
  - curl -d "repo=github.com/kubevirt/containerized-data-importer" https://goreportcard.com/checks

before_deploy:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

deploy:
  # Release :latest images
- provider: script
  script: make publish
  skip_cleanup: true
  on:
    branch: master
    repo: kubevirt/containerized-data-importer
 # Release versioned images
- provider: script
  script: make publish
  branches:
      only: /v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+){0,1}/
  on:
    tags: true
    repo: kubevirt/containerized-data-importer
- provider: releases
  branches:
    only: /v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+){0,1}/
  on:
    tags: true
    repo: kubevirt/containerized-data-importer
  api_key:
    secure: K+UCoeC2/anVmurHmewg1EocqAZ+Mu5CLstOAW7z4+schhflaVfGUcYhQUtI5U8OMZyiTKoAwfkLBWwR6mtMULSMl3TbeHilUO252woCjZ44XMswKh7c1Cfs3AmE0QnKbHLyGBxdVdx5vUqXOOgC3LCkUM5Keg6Nj31xJFpImtZknYSZGD/DJzTH85tFol+oAqbB1EpeHR0s6rPsIzU2r2yaAw2AJUuvNLso2IKxIHbMY94C00hK5qv1sRkhVpXNB+NlcNnM3+bSCCM8BUXLVLhg/J2ld4n02oU2k8P5NmzJ2AXsLXcivi8/fMBb2VDw5EgjanzJT7+YVCuVwjhhXBm10n5xFvJKsv/Eprmuqg2uGDVJpueKPcVSSdryZmUvfHHYdTp6kEoW8IVd8ga3oWQVKLe/hDF7DzVf+Ky6Iln/TRvEFY29DXsrF8cv/bA8sT3spaCmoYU+DCtGoQOiP9jb193YUD6ek3rtqLf3wdAIhlqr+AMZZHM4cpN65fd6GJV1qvZRvTvrbaoqjI29hjmHgxHAdMIT/Z52ivK94hBPbsZuRO7zWj+oLVGaAkTP0E3cjBCdK9guqiXGp/E+QGlKivwW2w3P6nbxc0+TXHe8Od2TZ4WacU1+3mPDLidQFl3qiU/3ZWjDAQANdCw2xjFpnbCgCGXKsbQ+hj1DOOc=
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - _out/cmd/cdi-controller/*
  - _out/cmd/cdi-importer/*
  - _out/cmd/cdi-apiserver/*
  - _out/cmd/cdi-cloner/*
  - _out/cmd/cdi-operator/*
  - _out/cmd/cdi-uploadproxy/*
  - _out/cmd/cdi-uploadserver/*
  - _out/manifests/*.yaml
  - _out/manifests/release/*.yaml
  - _out/manifests/templates/release/*.yaml.j2
  - _out/manifests/release/olm/*.yaml
  - _out/manifests/templates/release/olm/*.yaml.j2
  - _out/manifests/release/olm/bundle/*.yaml
  - _out/manifests/templates/release/olm/bundle/*.yaml.j2
  - manifests/example/*
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    tags: true
