apiVersion: v1
kind: Pod
metadata:
  name: data-importer
  namespace: images
spec:
  restartPolicy: Never
  containers:
  - name: importer
    image: docker.io/jcoperh/importer:latest
    imagePullPolicy: Always
    env:
    # Secret vars
    - name: IMPORTER_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: importer-secret
          key: accessKeyId
    - name: IMPORTER_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: importer-secret
          key: secretKey
    # ConfigMap vars
    - name: IMPORTER_URL
      valueFrom:
        configMapKeyRef:
          name: importer-config
          key: url
    - name: IMPORTER_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: importer-config
          key: endpoint
    - name: IMPORTER_OBJECT_PATH
      valueFrom:
        configMapKeyRef:
          name: importer-config
          key: objectPath
    - name: IMPORTER_DEST_PATH
      valueFrom:
        configMapKeyRef:
          name: importer-config
          key: writeToPath
    volumeMounts:
    - name: data-path
      mountPath: /image # MUST match importer configMap data.writeToPath
  volumes:
  - name: data-path
    hostPath:
      path: /image
