apiVersion: v1
kind: Pod
metadata:
  name: data-importer
  namespace: images
spec:
  containers:
  - name: data-importer
    image: importer   # local per `make importer-image`
    imagePullPolicy: IfNotPresent
    restartPolicy: Never
    env:
    - name: IMPORTER_SECRET_KEY
      valueFrom: # all secret values must be base64 encoded
        secretKeyRef:
          name: importer-pod-secret
          key: importer_secret_key
    - name: IMPORTER_ACCESS_KEY_ID
      valueFrom: # all secret values must be base64 encoded
        secretKeyRef:
          name: importer-pod-secret
          key: importer_access_key_id
    - name: IMPORTER_URL
      valueFrom:
        ConfigMapKeyRef:
          name: importer-pod-config
          key: importer_url
    - name: IMPORTER_ENDPOINT
      valueFrom:
        ConfigMapKeyRef:
          name: importer-pod-config
          key: importer_endpoint
    - name: IMPORTER_OBJECT_PATH
      valueFrom:
        ConfigMapKeyRef:
          name: importer-pod-config
          key: importer_object_path
    volumeMounts;
    - name: data-path
      mountPath: /...
  volumes:
  - name: data-path
    hostPath:
      path: /....
