apiVersion: v1
kind: Pod
metadata:
  name: data-importer
spec:
  restartPolicy: Never
  containers:
  - name: importer
    image: docker.io/jcoperh/importer:jcope-latest 
    imagePullPolicy: IfNotPresent
    env:
    - name: IMPORTER_URL
      valueFrom:
        configMapKeyRef:
          name: importer-pod-config
          key: importer_url
    - name: IMPORTER_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: importer-pod-config
          key: importer_endpoint
    - name: IMPORTER_OBJECT_PATH
      valueFrom:
        configMapKeyRef:
          name: importer-pod-config
          key: importer_object_path
    - name: IMPORTER_DESTINATION
      valueFrom:
        configMapKeyRef:
          name: importer-pod-config
          key: importer_destination
    volumeMounts:
    - name: data-path
      mountPath: /images
  volumes:
  - name: data-path
    hostPath:
      path: /home/ec2-user
