apiVersion: v1
kind: Pod
metadata:
  name: data-importer
spec:
  restartPolicy: Never
  containers:
  - name: importer
    image: jcoperh/importer:latest
    imagePullPolicy: Always
    env:
    # Secret vars
    - name: IMPORTER_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: importer-secret
          key: accessKeyId
    - name: IMPORTER_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: importer-secret
          key: secretKey
    # ConfigMap var
    - name: IMPORTER_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: importer-config
          key: endpoint
    volumeMounts:
    - name: data-path
      mountPath: /data
  volumes:
  - name: data-path
    persistentVolumeClaim:
      claimName: importer-pvc
