apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "importer-pvc"
  namespace: images
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
